#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE duel;
	GRANT ALL PRIVILEGES ON DATABASE duel TO $POSTGRES_USER;
	\c duel
    CREATE SCHEMA IF NOT EXISTS dbt;
    CREATE SCHEMA IF NOT EXISTS raw;
EOSQL